### ISSUE TITLE
Make repo private and push CSS file to public repo using GitHub Actions

### ISSUE THREAD

**Issue by nielslange** [wcasia/2023-website#53]
## Motivation

To ease the communication and workflows, we decided to move the theme code from https://github.com/wcasia/2023-theme to this repo. Initially, this repo was private. Once I migrated the theme code over, I noticed that https://asia.wordcamp.org/2023 cannot fetch the CSS file from a private repo, so I made it public. However, not all communication is meant to be public. Therefore, this repo should remain private.

## Tasks

- [ ] Create GitHub Action to push the CSS code from this repo into https://github.com/wcasia/2023-theme with each created PR.
- [ ] Fetch the CSS file from https://github.com/wcasia/2023-theme instead of from this repo.
- [ ] Make this repo private.
